LOGINN_BUTTON = "login-button"
ERROR_MESSAGE = "//*[@id='login_button_container']/div/form/div[3]/h3"
INPUT_USERNAME = "user-name"
INPUT_PASSWORD = "password"
LOCKED_USERNAME = "locked_out_user"
UNLOCKED_USERNAME = "standard_user"
PASSWORD = "secret_sauce"
MESSAGE_CLOSED = "/html/body/div/div/div[2]/div[1]/div/div/form/div[3]/h3/button"
INVENTORY_ITEM ="inventory_item"